apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-k8s-demo
  template:
    metadata:
      labels:
        app: node-k8s-demo
    spec:
      containers:
      - name: node-k8s-demo
        image: hello:01     # ✅ updated image name
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-k8s-service
spec:
  type: NodePort
  selector:
    app: node-k8s-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
