apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-nodeport
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090
  selector:
    app: prometheus
    component: server
